version: "3.9"

services:
  web:
    build: .
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done &&
     python manage.py migrate &&
     python manage.py loaddata fixtures/data.json &&
     python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code/
    env_file:
      - ./src/CourseStore/settings/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - ./src/CourseStore/settings/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
